#!/sbin/busybox sh

export BOOTREC_LED_RED="/sys/class/leds/led:rgb_red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/led:rgb_green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/led:rgb_blue/brightness"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p32 b 259 0"
export BOOTREC_FOTA="/dev/block/mmcblk0p32"
